/*=============================================================
  Realty Income REIT Agent - Analytics Views
  Step 5: Create analytical views for the agent to query
=============================================================*/

USE DATABASE REALTY_INCOME;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW PROPERTY_PERFORMANCE AS
SELECT
    p.PROPERTY_ID,
    p.PROPERTY_NAME,
    p.PROPERTY_TYPE,
    p.SECTOR,
    p.CITY,
    p.STATE,
    p.SQUARE_FOOTAGE,
    p.YEAR_BUILT,
    p.YEAR_ACQUIRED,
    p.ACQUISITION_PRICE,
    p.CURRENT_VALUATION,
    p.CAP_RATE,
    p.OCCUPANCY_STATUS,
    t.TENANT_NAME,
    t.INDUSTRY,
    t.CREDIT_RATING,
    l.LEASE_TYPE,
    l.LEASE_START_DATE,
    l.LEASE_END_DATE,
    l.ANNUAL_RENT,
    l.RENT_ESCALATION_RATE,
    l.REMAINING_TERM_MONTHS,
    l.TRIPLE_NET,
    l.STATUS AS LEASE_STATUS,
    fm.FISCAL_YEAR,
    fm.FISCAL_QUARTER,
    fm.NET_OPERATING_INCOME,
    fm.OCCUPANCY_RATE,
    fm.SAME_STORE_NOI_GROWTH,
    fm.FUNDS_FROM_OPERATIONS
FROM REALTY_INCOME.RAW.PROPERTIES p
LEFT JOIN REALTY_INCOME.RAW.LEASES l ON p.PROPERTY_ID = l.PROPERTY_ID
LEFT JOIN REALTY_INCOME.RAW.TENANTS t ON l.TENANT_ID = t.TENANT_ID
LEFT JOIN REALTY_INCOME.RAW.FINANCIAL_METRICS fm ON p.PROPERTY_ID = fm.PROPERTY_ID;

CREATE OR REPLACE VIEW PORTFOLIO_HEALTH AS
SELECT
    ps.REPORTING_DATE,
    ps.TOTAL_PROPERTIES,
    ps.TOTAL_SQUARE_FOOTAGE,
    ps.PORTFOLIO_OCCUPANCY_RATE,
    ps.WEIGHTED_AVG_LEASE_TERM,
    ps.TOTAL_ANNUALIZED_RENT,
    ps.INVESTMENT_GRADE_TENANTS_PCT,
    ps.DIVERSIFICATION_SCORE,
    ps.TOTAL_DEBT,
    ps.DEBT_TO_EBITDA_RATIO,
    ps.INTEREST_COVERAGE_RATIO,
    ps.DIVIDEND_PER_SHARE,
    ps.FFO_PER_SHARE,
    ps.AFFO_PER_SHARE,
    ps.PAYOUT_RATIO,
    md.STOCK_PRICE,
    md.MARKET_CAP,
    md.DIVIDEND_YIELD,
    md.PRICE_TO_FFO,
    md.PRICE_TO_AFFO,
    md.TOTAL_RETURN_YTD,
    md.TREASURY_10Y_YIELD,
    md.SPREAD_TO_TREASURY
FROM REALTY_INCOME.RAW.PORTFOLIO_SUMMARY ps
LEFT JOIN REALTY_INCOME.RAW.MARKET_DATA md
    ON md.MARKET_DATE = ps.REPORTING_DATE;

CREATE OR REPLACE VIEW LEASE_EXPIRATION_SCHEDULE AS
SELECT
    YEAR(l.LEASE_END_DATE) AS EXPIRATION_YEAR,
    QUARTER(l.LEASE_END_DATE) AS EXPIRATION_QUARTER,
    COUNT(*) AS LEASE_COUNT,
    SUM(l.ANNUAL_RENT) AS TOTAL_RENT_EXPIRING,
    AVG(l.RENT_ESCALATION_RATE) AS AVG_ESCALATION_RATE,
    COUNT(CASE WHEN t.CREDIT_RATING IN ('AAA','AA+','AA','AA-','A+','A','A-','BBB+','BBB','BBB-') THEN 1 END) AS INVESTMENT_GRADE_COUNT,
    COUNT(CASE WHEN l.TRIPLE_NET = TRUE THEN 1 END) AS NNN_LEASE_COUNT
FROM REALTY_INCOME.RAW.LEASES l
LEFT JOIN REALTY_INCOME.RAW.TENANTS t ON l.TENANT_ID = t.TENANT_ID
WHERE l.STATUS = 'Active'
GROUP BY YEAR(l.LEASE_END_DATE), QUARTER(l.LEASE_END_DATE)
ORDER BY EXPIRATION_YEAR, EXPIRATION_QUARTER;

CREATE OR REPLACE VIEW TENANT_CONCENTRATION AS
SELECT
    t.TENANT_NAME,
    t.INDUSTRY,
    t.CREDIT_RATING,
    t.PUBLIC_COMPANY,
    COUNT(DISTINCT l.PROPERTY_ID) AS PROPERTY_COUNT,
    SUM(l.ANNUAL_RENT) AS TOTAL_ANNUAL_RENT,
    ROUND(SUM(l.ANNUAL_RENT) / NULLIF((SELECT SUM(ANNUAL_RENT) FROM REALTY_INCOME.RAW.LEASES WHERE STATUS = 'Active'), 0) * 100, 2) AS PCT_OF_TOTAL_RENT,
    AVG(l.REMAINING_TERM_MONTHS) AS AVG_REMAINING_TERM,
    MIN(l.LEASE_END_DATE) AS EARLIEST_EXPIRATION,
    MAX(l.LEASE_END_DATE) AS LATEST_EXPIRATION
FROM REALTY_INCOME.RAW.TENANTS t
JOIN REALTY_INCOME.RAW.LEASES l ON t.TENANT_ID = l.TENANT_ID
WHERE l.STATUS = 'Active'
GROUP BY t.TENANT_NAME, t.INDUSTRY, t.CREDIT_RATING, t.PUBLIC_COMPANY
ORDER BY TOTAL_ANNUAL_RENT DESC;

CREATE OR REPLACE VIEW GEOGRAPHIC_DISTRIBUTION AS
SELECT
    p.STATE,
    COUNT(*) AS PROPERTY_COUNT,
    SUM(p.SQUARE_FOOTAGE) AS TOTAL_SQFT,
    AVG(p.CAP_RATE) AS AVG_CAP_RATE,
    SUM(p.CURRENT_VALUATION) AS TOTAL_VALUATION,
    COUNT(CASE WHEN p.OCCUPANCY_STATUS = 'Occupied' THEN 1 END)::FLOAT / COUNT(*) * 100 AS OCCUPANCY_PCT,
    SUM(l.ANNUAL_RENT) AS TOTAL_ANNUAL_RENT,
    AVG(r.RISK_SCORE) AS AVG_RISK_SCORE
FROM REALTY_INCOME.RAW.PROPERTIES p
LEFT JOIN REALTY_INCOME.RAW.LEASES l ON p.PROPERTY_ID = l.PROPERTY_ID
LEFT JOIN REALTY_INCOME.RAW.RISK_ASSESSMENTS r ON p.PROPERTY_ID = r.PROPERTY_ID
GROUP BY p.STATE
ORDER BY PROPERTY_COUNT DESC;

CREATE OR REPLACE VIEW RISK_DASHBOARD AS
SELECT
    r.PROPERTY_ID,
    p.PROPERTY_NAME,
    p.PROPERTY_TYPE,
    p.CITY,
    p.STATE,
    t.TENANT_NAME,
    t.CREDIT_RATING,
    r.ASSESSMENT_DATE,
    r.RISK_CATEGORY,
    r.RISK_SCORE,
    r.RISK_LEVEL,
    r.GEOGRAPHIC_RISK,
    r.TENANT_CREDIT_RISK,
    r.MARKET_RISK,
    r.INTEREST_RATE_RISK,
    r.ENVIRONMENTAL_RISK,
    r.LEASE_EXPIRATION_RISK,
    l.REMAINING_TERM_MONTHS,
    l.ANNUAL_RENT
FROM REALTY_INCOME.RAW.RISK_ASSESSMENTS r
JOIN REALTY_INCOME.RAW.PROPERTIES p ON r.PROPERTY_ID = p.PROPERTY_ID
LEFT JOIN REALTY_INCOME.RAW.LEASES l ON p.PROPERTY_ID = l.PROPERTY_ID
LEFT JOIN REALTY_INCOME.RAW.TENANTS t ON l.TENANT_ID = t.TENANT_ID;

CREATE OR REPLACE VIEW FINANCIAL_TREND AS
SELECT
    fm.FISCAL_YEAR,
    fm.FISCAL_QUARTER,
    fm.REPORTING_DATE,
    COUNT(DISTINCT fm.PROPERTY_ID) AS PROPERTIES_REPORTING,
    SUM(fm.GROSS_REVENUE) AS TOTAL_REVENUE,
    SUM(fm.NET_OPERATING_INCOME) AS TOTAL_NOI,
    SUM(fm.OPERATING_EXPENSES) AS TOTAL_OPEX,
    SUM(fm.CAPITAL_EXPENDITURES) AS TOTAL_CAPEX,
    SUM(fm.FUNDS_FROM_OPERATIONS) AS TOTAL_FFO,
    SUM(fm.ADJUSTED_FFO) AS TOTAL_AFFO,
    AVG(fm.OCCUPANCY_RATE) AS AVG_OCCUPANCY,
    AVG(fm.RENT_COLLECTION_RATE) AS AVG_COLLECTION_RATE,
    AVG(fm.SAME_STORE_NOI_GROWTH) AS AVG_SS_NOI_GROWTH
FROM REALTY_INCOME.RAW.FINANCIAL_METRICS fm
GROUP BY fm.FISCAL_YEAR, fm.FISCAL_QUARTER, fm.REPORTING_DATE
ORDER BY fm.FISCAL_YEAR, fm.FISCAL_QUARTER;

CREATE OR REPLACE VIEW MAINTENANCE_SUMMARY AS
SELECT
    p.PROPERTY_ID,
    p.PROPERTY_NAME,
    p.PROPERTY_TYPE,
    p.STATE,
    m.MAINTENANCE_TYPE,
    m.STATUS AS MAINTENANCE_STATUS,
    m.PRIORITY,
    m.ESTIMATED_COST,
    m.ACTUAL_COST,
    m.SCHEDULED_DATE,
    m.COMPLETED_DATE,
    DATEDIFF('day', m.SCHEDULED_DATE, COALESCE(m.COMPLETED_DATE, CURRENT_DATE())) AS DAYS_TO_COMPLETE,
    CASE WHEN m.ACTUAL_COST > m.ESTIMATED_COST THEN 'Over Budget'
         WHEN m.ACTUAL_COST <= m.ESTIMATED_COST THEN 'On/Under Budget'
         ELSE 'Pending' END AS BUDGET_STATUS
FROM REALTY_INCOME.RAW.MAINTENANCE_RECORDS m
JOIN REALTY_INCOME.RAW.PROPERTIES p ON m.PROPERTY_ID = p.PROPERTY_ID;
