/*=============================================================
  Realty Income REIT Agent - Database & Schema Setup
  Step 1: Create database, schemas, warehouse, and stages
=============================================================*/

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS REALTY_INCOME;

USE DATABASE REALTY_INCOME;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS ML;
CREATE SCHEMA IF NOT EXISTS AGENT;

CREATE WAREHOUSE IF NOT EXISTS REALTY_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE;

USE WAREHOUSE REALTY_WH;

CREATE STAGE IF NOT EXISTS REALTY_INCOME.RAW.DOCS_STAGE
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE STAGE IF NOT EXISTS REALTY_INCOME.RAW.ML_STAGE
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
