/*=============================================================
  Realty Income REIT Agent - Table Definitions
  Step 2: Create all core tables for the REIT data model
=============================================================*/

USE DATABASE REALTY_INCOME;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE PROPERTIES (
    PROPERTY_ID VARCHAR(20) PRIMARY KEY,
    PROPERTY_NAME VARCHAR(200),
    PROPERTY_TYPE VARCHAR(50),
    SECTOR VARCHAR(100),
    ADDRESS VARCHAR(300),
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    ZIP_CODE VARCHAR(10),
    COUNTRY VARCHAR(50) DEFAULT 'United States',
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    SQUARE_FOOTAGE NUMBER(12,0),
    YEAR_BUILT NUMBER(4,0),
    YEAR_ACQUIRED NUMBER(4,0),
    ACQUISITION_PRICE NUMBER(18,2),
    CURRENT_VALUATION NUMBER(18,2),
    CAP_RATE FLOAT,
    OCCUPANCY_STATUS VARCHAR(20),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE TENANTS (
    TENANT_ID VARCHAR(20) PRIMARY KEY,
    TENANT_NAME VARCHAR(200),
    INDUSTRY VARCHAR(100),
    CREDIT_RATING VARCHAR(10),
    PARENT_COMPANY VARCHAR(200),
    HEADQUARTERS_STATE VARCHAR(50),
    ANNUAL_REVENUE NUMBER(18,2),
    EMPLOYEE_COUNT NUMBER(10,0),
    PUBLIC_COMPANY BOOLEAN,
    TICKER_SYMBOL VARCHAR(10),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE LEASES (
    LEASE_ID VARCHAR(20) PRIMARY KEY,
    PROPERTY_ID VARCHAR(20) REFERENCES PROPERTIES(PROPERTY_ID),
    TENANT_ID VARCHAR(20) REFERENCES TENANTS(TENANT_ID),
    LEASE_TYPE VARCHAR(50),
    LEASE_START_DATE DATE,
    LEASE_END_DATE DATE,
    MONTHLY_RENT NUMBER(12,2),
    ANNUAL_RENT NUMBER(14,2),
    RENT_ESCALATION_RATE FLOAT,
    RENT_ESCALATION_TYPE VARCHAR(50),
    LEASE_TERM_MONTHS NUMBER(6,0),
    REMAINING_TERM_MONTHS NUMBER(6,0),
    RENEWAL_OPTIONS NUMBER(3,0),
    TRIPLE_NET BOOLEAN DEFAULT TRUE,
    STATUS VARCHAR(20) DEFAULT 'Active',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE FINANCIAL_METRICS (
    METRIC_ID VARCHAR(20) PRIMARY KEY,
    PROPERTY_ID VARCHAR(20) REFERENCES PROPERTIES(PROPERTY_ID),
    FISCAL_YEAR NUMBER(4,0),
    FISCAL_QUARTER NUMBER(1,0),
    REPORTING_DATE DATE,
    GROSS_REVENUE NUMBER(14,2),
    NET_OPERATING_INCOME NUMBER(14,2),
    OPERATING_EXPENSES NUMBER(14,2),
    CAPITAL_EXPENDITURES NUMBER(14,2),
    FUNDS_FROM_OPERATIONS NUMBER(14,2),
    ADJUSTED_FFO NUMBER(14,2),
    DEBT_SERVICE NUMBER(14,2),
    OCCUPANCY_RATE FLOAT,
    RENT_COLLECTION_RATE FLOAT,
    SAME_STORE_NOI_GROWTH FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PORTFOLIO_SUMMARY (
    SUMMARY_ID VARCHAR(20) PRIMARY KEY,
    REPORTING_DATE DATE,
    TOTAL_PROPERTIES NUMBER(6,0),
    TOTAL_SQUARE_FOOTAGE NUMBER(14,0),
    PORTFOLIO_OCCUPANCY_RATE FLOAT,
    WEIGHTED_AVG_LEASE_TERM FLOAT,
    TOTAL_ANNUALIZED_RENT NUMBER(18,2),
    INVESTMENT_GRADE_TENANTS_PCT FLOAT,
    DIVERSIFICATION_SCORE FLOAT,
    TOTAL_DEBT NUMBER(18,2),
    DEBT_TO_EBITDA_RATIO FLOAT,
    INTEREST_COVERAGE_RATIO FLOAT,
    DIVIDEND_PER_SHARE NUMBER(8,4),
    FFO_PER_SHARE NUMBER(8,4),
    AFFO_PER_SHARE NUMBER(8,4),
    PAYOUT_RATIO FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE MARKET_DATA (
    MARKET_ID VARCHAR(20) PRIMARY KEY,
    MARKET_DATE DATE,
    STOCK_PRICE NUMBER(10,4),
    MARKET_CAP NUMBER(18,2),
    DIVIDEND_YIELD FLOAT,
    PRICE_TO_FFO FLOAT,
    PRICE_TO_AFFO FLOAT,
    TOTAL_RETURN_YTD FLOAT,
    BETA FLOAT,
    VOLUME NUMBER(14,0),
    SP500_RETURN_YTD FLOAT,
    TREASURY_10Y_YIELD FLOAT,
    SPREAD_TO_TREASURY FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DOCUMENTS (
    DOC_ID VARCHAR(20) PRIMARY KEY,
    DOC_TYPE VARCHAR(50),
    DOC_TITLE VARCHAR(500),
    DOC_DATE DATE,
    FISCAL_YEAR NUMBER(4,0),
    FISCAL_QUARTER NUMBER(1,0),
    CONTENT TEXT,
    SUMMARY TEXT,
    SOURCE_URL VARCHAR(500),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RISK_ASSESSMENTS (
    RISK_ID VARCHAR(20) PRIMARY KEY,
    PROPERTY_ID VARCHAR(20) REFERENCES PROPERTIES(PROPERTY_ID),
    ASSESSMENT_DATE DATE,
    RISK_CATEGORY VARCHAR(50),
    RISK_SCORE FLOAT,
    RISK_LEVEL VARCHAR(20),
    GEOGRAPHIC_RISK FLOAT,
    TENANT_CREDIT_RISK FLOAT,
    MARKET_RISK FLOAT,
    INTEREST_RATE_RISK FLOAT,
    ENVIRONMENTAL_RISK FLOAT,
    LEASE_EXPIRATION_RISK FLOAT,
    NOTES TEXT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE MAINTENANCE_RECORDS (
    MAINTENANCE_ID VARCHAR(20) PRIMARY KEY,
    PROPERTY_ID VARCHAR(20) REFERENCES PROPERTIES(PROPERTY_ID),
    MAINTENANCE_TYPE VARCHAR(50),
    DESCRIPTION TEXT,
    SCHEDULED_DATE DATE,
    COMPLETED_DATE DATE,
    ESTIMATED_COST NUMBER(12,2),
    ACTUAL_COST NUMBER(12,2),
    VENDOR VARCHAR(200),
    STATUS VARCHAR(20),
    PRIORITY VARCHAR(20),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
